"""
SDK Client V2 — Real LLM execution with simulation fallback.

Wraps the LLM adapter layer for agent step execution. Each workflow step
is executed via a configured LLM provider with streaming output. Falls
back to V1 simulation when no LLM config is available.
"""

import asyncio
import random
from datetime import datetime
from typing import Dict, Any, List, Optional

from agent_engine.output_stream import OutputStreamManager
from llm.base import ChatMessage


class SDKClient:
    """
    Executes agent workflow steps via LLM providers.

    Priority:
      1. Real LLM call (if llm_config has a valid api_key and provider is reachable)
      2. V1 simulation fallback (hardcoded domain-specific templates)

    Each step streams output chunks through OutputStreamManager in real time.
    """

    # ── V1 Simulation templates (fallback) ─────────────────────────────

    _domain_outputs = {
        "adas": {
            "analysis": [
                "Analyzing sensor configuration for {agent_name}...",
                "Camera placement: Front-wide (120deg FOV), Front-narrow (30deg FOV), Side-rear (90deg FOV each), Rear (120deg FOV)",
                "Radar configuration: Front long-range (250m), Corner short-range (80m each)",
                "LiDAR: Roof-mounted 360deg, 128 layers, 0.1deg angular resolution",
                "Computing sensor fusion overlap matrices for redundancy assessment...",
                "Object detection pipeline: YOLO-based with TensorRT optimization, target latency < 50ms",
                "Tracking algorithm: Extended Kalman Filter with IMM (Interacting Multiple Model)",
                "Sensor fusion architecture: Centralized EKF with asynchronous measurement updates",
                "Validating against ISO 26262 ASIL B(D) requirements for perception subsystem...",
                "Generating perception pipeline specification document...",
            ],
            "code": [
                "// sensor_fusion.c - Auto-generated by {agent_name}",
                "// ADAS Sensor Fusion Module",
                "// Compliant with ISO 26262 ASIL B(D)",
                "",
                '#include "sensor_fusion.h"',
                '#include "kalman_filter.h"',
                '#include "coordinate_transform.h"',
                "",
                "typedef struct {",
                "    SensorData camera_front_wide;",
                "    SensorData camera_front_narrow;",
                "    SensorData radar_front_long;",
                "    SensorData radar_corner[4];",
                "    SensorData lidar_roof;",
                "    FusionState state;",
                "} SensorFusionContext;",
                "",
                "void sensor_fusion_init(SensorFusionContext* ctx) {",
                "    ekf_init(&ctx->state, STATE_DIM, MEAS_DIM);",
                "    initialize_coordinate_frames();",
                "    calibrate_sensor_extrinsics(ctx);",
                "}",
                "",
                "FusionResult sensor_fusion_process(SensorFusionContext* ctx) {",
                "    // Step 1: Time-synchronize all sensor measurements",
                "    sync_sensor_timestamps(ctx);",
                "    // Step 2: Transform to vehicle coordinate frame",
                "    transform_to_ego_frame(ctx);",
                "    // Step 3: Data association using Hungarian algorithm",
                "    associate_measurements(ctx);",
                "    // Step 4: EKF update cycle",
                "    ekf_predict(&ctx->state);",
                "    ekf_update(&ctx->state, get_measurement_vector(ctx));",
                "    // Step 5: Track management",
                "    manage_tracks(&ctx->state);",
                "    return package_fusion_result(&ctx->state);",
                "}",
            ],
            "deliverable": [
                "# ADAS Perception Pipeline Specification",
                "",
                "## 1. Sensor Suite Configuration",
                "| Sensor | Quantity | Position | FOV | Range |",
                "|--------|----------|----------|-----|-------|",
                "| Camera (wide) | 1 | Front | 120deg | 150m |",
                "| Camera (narrow) | 1 | Front | 30deg | 250m |",
                "| Radar (long) | 1 | Front | 15deg | 250m |",
                "| Radar (corner) | 4 | Corners | 150deg | 80m |",
                "| LiDAR | 1 | Roof | 360deg | 200m |",
                "",
                "## 2. Object Detection Performance",
                "- Vehicle detection: > 95% recall @ 200m",
                "- Pedestrian detection: > 90% recall @ 80m",
                "- Cyclist detection: > 85% recall @ 100m",
                "",
                "## 3. Tracking Performance",
                "- Track initiation latency: < 500ms",
                "- Track maintenance: > 99% continuity",
                "- Maximum tracked objects: 256",
                "",
                "## 4. Safety Analysis",
                "- ASIL Level: B(D)",
                "- FTTI: 200ms",
                "- Safe state: Degraded perception mode with reduced speed limit",
            ],
        },
        "functional safety": {
            "analysis": [
                "Initiating Hazard Analysis and Risk Assessment (HARA) per ISO 26262-3...",
                "Identifying item definition and boundaries for {agent_name}...",
                "Analyzing operational situations and driving scenarios...",
                "Evaluating hazardous events for malfunctioning behavior...",
                "Determining Controllability (C), Exposure (E), and Severity (S) ratings...",
                "Computing ASIL levels: ASIL A through ASIL D based on C+E+S...",
                "Documenting safety goals with safe states and fault tolerant time intervals...",
                "Performing FMEA (Failure Mode and Effects Analysis)...",
                "Identifying single-point faults, latent faults, and common-cause failures...",
                "Generating safety case argumentation in GSN (Goal Structuring Notation)...",
            ],
            "code": [
                "# HARA Analysis Module - Auto-generated by {agent_name}",
                "# Compliance: ISO 26262-3:2018",
                "",
                "class HazardAnalysis:",
                '    """Hazard Analysis and Risk Assessment per ISO 26262-3."""',
                "",
                "    def __init__(self, item_definition):",
                "        self.item = item_definition",
                "        self.hazards = []",
                "        self.safety_goals = []",
                "",
                "    def identify_hazards(self, malfunctions, operational_situations):",
                '        """Identify hazardous events from malfunctions in operational situations."""',
                "        for mf in malfunctions:",
                "            for situation in operational_situations:",
                "                hazard = self.evaluate_hazard(mf, situation)",
                "                if hazard.risk_level != 'QM':",
                "                    self.hazards.append(hazard)",
                "",
                "    def determine_asil(self, severity, exposure, controllability):",
                '        """Determine ASIL level from S, E, C parameters."""',
                "        asil_matrix = {",
                "            ('S3', 'E4', 'C3'): 'ASIL D',",
                "            ('S3', 'E4', 'C2'): 'ASIL C',",
                "            ('S3', 'E3', 'C3'): 'ASIL C',",
                "            ('S2', 'E4', 'C3'): 'ASIL B',",
                "            ('S2', 'E3', 'C2'): 'ASIL A',",
                "        }",
                "        return asil_matrix.get((severity, exposure, controllability), 'QM')",
                "",
                "    def derive_safety_goals(self, hazards):",
                '        """Derive safety goals from identified hazards."""',
                "        for hazard in hazards:",
                "            sg = SafetyGoal(",
                "                id=f'SG-{{len(self.safety_goals)+1:03d}}',",
                "                hazard=hazard,",
                "                safe_state=hazard.derive_safe_state(),",
                "                ftti=hazard.compute_ftti(),",
                "                asil=hazard.asil_level",
                "            )",
                "            self.safety_goals.append(sg)",
            ],
            "deliverable": [
                "# Hazard Analysis and Risk Assessment Report",
                "",
                "## 1. Item Definition",
                "- **System**: L2 Highway Autopilot System",
                "- **Functions**: Adaptive Cruise Control, Lane Keeping Assist, Automatic Emergency Braking",
                "- **Boundaries**: Sensor suite through actuation control",
                "",
                "## 2. Hazard Identification Summary",
                "| Hazard ID | Malfunction | Operational Situation | Hazardous Event |",
                "|-----------|-------------|----------------------|-----------------|",
                "| HZ-001 | Unintended braking | Highway driving, heavy traffic | Rear-end collision |",
                "| HZ-002 | Loss of lane detection | Highway curve, night + rain | Lane departure |",
                "| HZ-003 | False object detection | Urban, pedestrian crossing | Unnecessary evasive maneuver |",
                "",
                "## 3. ASIL Determination",
                "| Hazard | S | E | C | ASIL | Safety Goal |",
                "|--------|---|---|---|------|-------------|",
                "| HZ-001 | S3 | E4 | C2 | ASIL C | Prevent unintended braking above 0.3g |",
                "| HZ-002 | S3 | E4 | C3 | ASIL D | Maintain lane detection reliability > 99% |",
                "| HZ-003 | S2 | E3 | C2 | ASIL A | Prevent false evasive maneuvers |",
            ],
        },
        "autosar": {
            "analysis": [
                "Analyzing system requirements for AUTOSAR architecture with {agent_name}...",
                "Identifying SWC (Software Component) types and compositions...",
                "Defining Port-Interface mappings between SWCs...",
                "Configuring RTE (Runtime Environment) communication patterns...",
                "Designing BSW (Basic Software) layer configuration...",
                "Mapping runnable entities to OS tasks with scheduling analysis...",
                "Validating timing constraints and resource utilization...",
                "Generating ARXML configuration fragments...",
                "Performing consistency checks across system description...",
            ],
            "code": [
                "<!-- AUTOSAR System Description - Auto-generated by {agent_name} -->",
                '<!-- Compliance: AUTOSAR Adaptive R20-11 -->',
                "",
                '<AR-PACKAGES>',
                '    <AR-PACKAGE>',
                '        <SHORT-NAME>SwcImplementation</SHORT-NAME>',
                '        <ELEMENTS>',
                '            <SWC-IMPLEMENTATION>',
                '                <SHORT-NAME>SensorFusion_Swc</SHORT-NAME>',
                '                <BEHAVIOR>',
                '                    <SWC-INTERNAL-BEHAVIOR>',
                '                        <SHORT-NAME>SensorFusion_Behavior</SHORT-NAME>',
                '                        <RUNNABLES>',
                '                            <RUNNABLE-ENTITY>',
                '                                <SHORT-NAME>RE_SensorProcessing</SHORT-NAME>',
                '                                <MINIMUM-START-INTERVAL>0.01</MINIMUM-START-INTERVAL>',
                '                                <CAN-BE-INVOKED-CONCURRENTLY>false</CAN-BE-INVOKED-CONCURRENTLY>',
                '                            </RUNNABLE-ENTITY>',
                '                            <RUNNABLE-ENTITY>',
                '                                <SHORT-NAME>RE_FusionAlgorithm</SHORT-NAME>',
                '                                <MINIMUM-START-INTERVAL>0.05</MINIMUM-START-INTERVAL>',
                '                            </RUNNABLE-ENTITY>',
                '                        </RUNNABLES>',
                '                    </SWC-INTERNAL-BEHAVIOR>',
                '                </BEHAVIOR>',
                '            </SWC-IMPLEMENTATION>',
                '        </ELEMENTS>',
                '    </AR-PACKAGE>',
                '</AR-PACKAGES>',
            ],
            "deliverable": [
                "# AUTOSAR Architecture Specification",
                "",
                "## 1. Software Component Overview",
                "| SWC Name | Type | Responsibilities |",
                "|----------|------|-----------------|",
                "| SensorFusion_Swc | Application SWC | Multi-sensor data fusion, object tracking |",
                "| VehicleState_Swc | Application SWC | Ego motion estimation, state propagation |",
                "| SafetyMonitor_Swc | Application SWC | Safety goal violation monitoring |",
                "",
                "## 2. Runnable to Task Mapping",
                "| Runnable | OS Task | Period (ms) | Priority | Core |",
                "|----------|---------|-------------|----------|------|",
                "| RE_SensorProcessing | Task_10ms | 10 | 5 | Core0 |",
                "| RE_FusionAlgorithm | Task_50ms | 50 | 7 | Core0 |",
                "| RE_SafetyCheck | Task_100ms | 100 | 10 | Core1 |",
            ],
        },
        "sotif": {
            "analysis": [
                "Initiating SOTIF analysis per ISO 21448 with {agent_name}...",
                "Identifying functional insufficiencies and performance limitations...",
                "Analyzing triggering conditions for hazardous scenarios...",
                "Evaluating sensor limitations in degraded environmental conditions...",
                "Assessing perception algorithm performance boundaries...",
                "Defining validation strategies for unknown unsafe scenarios...",
                "Developing SOTIF use case catalog and acceptance criteria...",
            ],
            "code": [],
            "deliverable": [
                "# SOTIF Analysis Report (ISO 21448)",
                "",
                "## 1. Scope and System Definition",
                "- System under analysis: L2+ Highway Pilot",
                "- SOTIF-relevant functions: Object detection, classification, trajectory prediction",
                "",
                "## 2. Identified Functional Insufficiencies",
                "| ID | Insufficiency | Trigger Condition | Potential Hazard | Area |",
                "|----|--------------|-------------------|-----------------|------|",
                "| FI-01 | CNN false negative on occluded pedestrians | Urban intersection, partial occlusion | Collision with pedestrian | Area 2 |",
                "| FI-02 | Lane detection failure in low sun angle | Driving directly into sunrise/sunset | Unintended lane departure | Area 2 |",
                "| FI-03 | Radar ghost targets from tunnel walls | Tunnel entry | Unnecessary emergency braking | Area 2 |",
            ],
        },
        "diagnostics": {
            "analysis": [
                "Analyzing diagnostic requirements per ISO 14229 (UDS) with {agent_name}...",
                "Defining Diagnostic Trouble Codes (DTCs) for subsystem monitoring...",
                "Designing diagnostic service sequences (0x10, 0x22, 0x2E, 0x31, etc.)...",
                "Configuring DID (Data Identifier) mappings for read/write services...",
                "Implementing security access (0x27) sequence for protected services...",
                "Defining routine control (0x31) sequences for actuator testing...",
                "Generating ODX/PDX diagnostic database...",
            ],
            "code": [
                "// Diagnostic Service Implementation - Auto-generated by {agent_name}",
                "// Compliance: ISO 14229-1 (UDS), ISO 15765-2 (DoCAN)",
                "",
                '#include "uds_server.h"',
                '#include "dtc_manager.h"',
                '#include "security_access.h"',
                "",
                "typedef enum {",
                "    DTC_SENSOR_FAULT       = 0xC10001,",
                "    DTC_COMMUNICATION_LOSS = 0xC10002,",
                "    DTC_CALIBRATION_ERROR  = 0xC10003,",
                "    DTC_OVER_TEMPERATURE   = 0xC10004,",
                "    DTC_VOLTAGE_OUT_RANGE  = 0xC10005,",
                "} DiagnosticTroubleCode;",
                "",
                "UDS_Response uds_service_handler(UDS_Request* req) {",
                "    switch(req->sid) {",
                "        case 0x10:  // Diagnostic Session Control",
                "            return handle_session_control(req->sub_function);",
                "        case 0x22:  // Read Data By Identifier",
                "            return handle_read_did(req->data_identifier);",
                "        case 0x2E:  // Write Data By Identifier",
                "            return handle_write_did(req->data_identifier, req->data);",
                "        case 0x19:  // Read DTC Information",
                "            return handle_read_dtc(req->sub_function, req->dtc_mask);",
                "        case 0x14:  // Clear Diagnostic Information",
                "            return handle_clear_dtc(req->group_of_dtc);",
                "        case 0x31:  // Routine Control",
                "            return handle_routine(req->routine_id, req->routine_ctrl);",
                "        case 0x27:  // Security Access",
                "            return handle_security_access(req->sub_function, req->key);",
                "        case 0x3E:  // Tester Present",
                "            return handle_tester_present(req->sub_function);",
                "        default:",
                "            return neg_response(req->sid, NRC_SERVICE_NOT_SUPPORTED);",
                "    }",
                "}",
            ],
            "deliverable": [
                "# Diagnostic Specification",
                "",
                "## 1. Diagnostic Trouble Codes",
                "| DTC | Description | Monitoring Strategy | FDC |",
                "|-----|-------------|-------------------|-----|",
                "| C10001 | Sensor signal out of range | Continuous, debounce 100ms | 0x51 |",
                "| C10002 | CAN communication loss | Continuous, timeout 500ms | 0x52 |",
                "| C10003 | Sensor calibration data corrupted | Power-up, checksum verification | 0x53 |",
                "| C10004 | ECU over-temperature | Continuous, threshold 125C | 0x54 |",
                "| C10005 | Supply voltage out of range | Continuous, 9V-16V window | 0x55 |",
                "",
                "## 2. Supported UDS Services",
                "| SID | Service | Sub-functions |",
                "|-----|---------|--------------|",
                "| 0x10 | Diagnostic Session Control | Default (0x01), Programming (0x02), Extended (0x03) |",
                "| 0x22 | Read Data By Identifier | DID 0xF100-0xF1FF |",
                "| 0x2E | Write Data By Identifier | DID 0xF200-0xF20F |",
                "| 0x19 | Read DTC Information | 0x01-0x0A, 0x42 |",
            ],
        },
    }

    _generic_outputs = {
        "analysis": [
            "Initializing {agent_name} agent for domain analysis...",
            "Loading agent capabilities and skill definitions...",
            "Parsing input context files and instructions...",
            "Analyzing requirements and constraints...",
            "Generating output based on domain-specific guidelines...",
            "Validating outputs against industry standards...",
            "Packaging deliverables for review...",
        ],
        "code": [
            "# Auto-generated by {agent_name}",
            "# Domain: {domain}",
            "",
            "def process(input_data):",
            '    """Process input according to {agent_name} specifications."""',
            "    # Step 1: Validate inputs",
            "    validated = validate_inputs(input_data)",
            "    # Step 2: Core processing",
            "    result = core_process(validated)",
            "    # Step 3: Post-process",
            "    output = post_process(result)",
            "    return output",
        ],
        "deliverable": [
            "# {step_name} Output",
            "",
            "## Analysis Results",
            "Analysis completed successfully by {agent_name}.",
            "",
            "## Key Findings",
            "- Input requirements were parsed and validated",
            "- Domain-specific processing completed",
            "- Outputs validated against relevant standards",
            "",
            "## Next Steps",
            "- Review the generated outputs",
            "- Confirm or request modifications",
            "- Continue to next workflow step",
        ],
    }

    # ── Public API ────────────────────────────────────────────────────

    async def execute_step(
        self,
        agent_name: str,
        step_config: Dict[str, Any],
        step_index: int,
        node_id: str,
        output_stream: OutputStreamManager,
        context_files: List[str] = None,
        user_instruction: str = "",
        agent_domain: str = "",
        llm_config: Any = None,
        workflow_steps: List[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Execute a single workflow step.

        Uses real LLM when llm_config has a valid api_key, otherwise falls
        back to V1 simulation templates.

        Args:
            agent_name: Name of the agent being executed
            step_config: Step definition dict (name, description, type, etc.)
            step_index: Zero-based step index
            node_id: Node identifier for output streaming
            output_stream: OutputStreamManager for streaming output
            context_files: List of context file paths
            user_instruction: Additional user instruction
            agent_domain: Agent's domain (adas, functional safety, etc.)
            llm_config: LLMConfigRequest with provider, api_key, model, base_url
            workflow_steps: All workflow steps for context

        Returns:
            Dict with step results (summary, output, deliverable_preview, etc.)
        """
        context_files = context_files or []
        workflow_steps = workflow_steps or []
        step_name = step_config.get("name", f"Step {step_index + 1}")
        step_desc = step_config.get("description", step_config.get("task", ""))

        # Try real LLM execution
        if self._has_llm_config(llm_config):
            try:
                return await self._execute_with_llm(
                    agent_name=agent_name,
                    step_name=step_name,
                    step_desc=step_desc,
                    step_index=step_index,
                    node_id=node_id,
                    output_stream=output_stream,
                    context_files=context_files,
                    user_instruction=user_instruction,
                    agent_domain=agent_domain,
                    llm_config=llm_config,
                    workflow_steps=workflow_steps,
                )
            except Exception as e:
                await output_stream.push(node_id, "output", {
                    "text": f"[WARN] LLM call failed ({e}), falling back to simulation...",
                    "step_index": step_index,
                    "timestamp": datetime.utcnow().isoformat(),
                })

        # Fallback: V1 simulation
        return await self._execute_simulated(
            agent_name=agent_name,
            step_config=step_config,
            step_index=step_index,
            node_id=node_id,
            output_stream=output_stream,
            agent_domain=agent_domain,
        )

    async def _execute_with_llm(
        self,
        agent_name: str,
        step_name: str,
        step_desc: str,
        step_index: int,
        node_id: str,
        output_stream: OutputStreamManager,
        context_files: List[str],
        user_instruction: str,
        agent_domain: str,
        llm_config: Any,
        workflow_steps: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Execute a step via real LLM with streaming output."""

        from llm.factory import create_provider

        provider = create_provider(
            provider=llm_config.provider,
            api_key=llm_config.api_key,
            model=llm_config.model,
            base_url=llm_config.base_url or None,
            temperature=0.3,
            max_tokens=8192,
        )

        # Build system prompt
        system_prompt = self._build_system_prompt(
            agent_name, agent_domain, workflow_steps, step_name
        )

        # Build user prompt
        user_prompt = self._build_user_prompt(
            step_name, step_desc, context_files, user_instruction, step_index, workflow_steps
        )

        messages = [
            ChatMessage(role="system", content=system_prompt),
            ChatMessage(role="user", content=user_prompt),
        ]

        # Stream LLM output
        full_text = []
        await output_stream.push(node_id, "output", {
            "text": f"--- {step_name} (via {llm_config.model}) ---",
            "step_index": step_index,
            "timestamp": datetime.utcnow().isoformat(),
        })

        try:
            async for chunk in provider.chat_stream(messages):
                if chunk.content:
                    full_text.append(chunk.content)
                    await output_stream.push(node_id, "output", {
                        "text": chunk.content,
                        "step_index": step_index,
                        "content_type": "llm_stream",
                        "timestamp": datetime.utcnow().isoformat(),
                    })
        finally:
            try:
                await provider.close()
            except Exception:
                pass

        full_output = "".join(full_text)
        summary = (
            f"Step '{step_name}' completed via {llm_config.model}. "
            f"Generated {len(full_output)} characters of analysis."
        )

        return {
            "step_index": step_index,
            "step_name": step_name,
            "summary": summary,
            "output": full_output,
            "output_lines": full_text,
            "deliverable_preview": full_output[:2000],
            "code_artifacts": self._extract_code_blocks(full_output),
            "model": llm_config.model,
            "provider": llm_config.provider,
            "timestamp": datetime.utcnow().isoformat(),
        }

    async def _execute_simulated(
        self,
        agent_name: str,
        step_config: Dict[str, Any],
        step_index: int,
        node_id: str,
        output_stream: OutputStreamManager,
        agent_domain: str = "",
    ) -> Dict[str, Any]:
        """V1 simulation fallback with domain-specific templates."""
        step_name = step_config.get("name", f"Step {step_index + 1}")
        domain_key = self._normalize_domain(agent_domain)
        outputs = self._domain_outputs.get(domain_key, self._generic_outputs)

        def _safe_fmt(text: str) -> str:
            return text.replace("{agent_name}", agent_name).replace("{domain}", agent_domain).replace("{step_name}", step_name)

        analysis_lines = [_safe_fmt(line) for line in outputs.get("analysis", self._generic_outputs["analysis"])]
        code_lines = [_safe_fmt(line) for line in outputs.get("code", self._generic_outputs["code"])]
        deliverable_lines = [_safe_fmt(line) for line in outputs.get("deliverable", self._generic_outputs["deliverable"])]

        full_output = []

        # Phase 1: Analysis
        for line in analysis_lines:
            await asyncio.sleep(random.uniform(0.1, 0.4))
            await output_stream.push(node_id, "output", {
                "text": line,
                "step_index": step_index,
                "timestamp": datetime.utcnow().isoformat(),
            })
            full_output.append(line)

        # Phase 2: Code
        if code_lines:
            await output_stream.push(node_id, "output", {
                "text": "--- Generating code artifacts ---",
                "step_index": step_index,
                "timestamp": datetime.utcnow().isoformat(),
            })
            for line in code_lines:
                await asyncio.sleep(random.uniform(0.05, 0.15))
                await output_stream.push(node_id, "output", {
                    "text": line,
                    "step_index": step_index,
                    "content_type": "code",
                    "timestamp": datetime.utcnow().isoformat(),
                })
                full_output.append(line)

        # Phase 3: Deliverable
        await output_stream.push(node_id, "output", {
            "text": f"\n--- {step_name} Deliverable Preview ---",
            "step_index": step_index,
            "timestamp": datetime.utcnow().isoformat(),
        })
        for line in deliverable_lines:
            await asyncio.sleep(random.uniform(0.05, 0.15))
            await output_stream.push(node_id, "output", {
                "text": line,
                "step_index": step_index,
                "content_type": "deliverable",
                "timestamp": datetime.utcnow().isoformat(),
            })
            full_output.append(line)

        await asyncio.sleep(random.uniform(0.2, 0.5))

        summary = (
            f"Step '{step_name}' completed successfully. "
            f"Generated {len(deliverable_lines)} lines of deliverable output "
            f"across {len(analysis_lines)} analysis items."
        )

        return {
            "step_index": step_index,
            "step_name": step_name,
            "summary": summary,
            "output": "\n".join(full_output),
            "output_lines": full_output,
            "deliverable_preview": "\n".join(deliverable_lines),
            "code_artifacts": "\n".join(code_lines) if code_lines else "",
            "timestamp": datetime.utcnow().isoformat(),
        }

    async def execute_full_workflow(
        self,
        agent_name: str,
        workflow_steps: List[Dict[str, Any]],
        node_id: str,
        output_stream: OutputStreamManager,
        context_files: List[str] = None,
        user_instruction: str = "",
        agent_domain: str = "",
        llm_config: Any = None,
    ) -> List[Dict[str, Any]]:
        """Execute an entire workflow sequentially."""
        results = []
        for i, step in enumerate(workflow_steps):
            result = await self.execute_step(
                agent_name=agent_name,
                step_config=step,
                step_index=i,
                node_id=node_id,
                output_stream=output_stream,
                context_files=context_files,
                user_instruction=user_instruction,
                agent_domain=agent_domain,
                llm_config=llm_config,
                workflow_steps=workflow_steps,
            )
            results.append(result)
        return results

    # ── Private helpers ───────────────────────────────────────────────

    @staticmethod
    def _has_llm_config(llm_config: Any) -> bool:
        """Check if llm_config is valid for real LLM calls."""
        if llm_config is None:
            return False
        api_key = getattr(llm_config, "api_key", "") or ""
        return bool(api_key.strip())

    def _build_system_prompt(
        self, agent_name: str, domain: str,
        workflow_steps: List[Dict[str, Any]], step_name: str,
    ) -> str:
        """Build system prompt for agent execution."""
        steps_summary = "\n".join(
            f"  {i+1}. {s.get('name', f'Step {i+1}')}"
            for i, s in enumerate(workflow_steps)
        ) if workflow_steps else ""

        return (
            f"You are {agent_name}, an automotive software engineering agent.\n"
            f"Domain: {domain}\n\n"
            f"## Workflow Context\n"
            f"Current step: {step_name}\n"
            f"Workflow steps:\n{steps_summary}\n\n"
            f"## Instructions\n"
            f"1. Provide detailed, technically accurate analysis specific to the automotive domain\n"
            f"2. Reference relevant standards (ISO 26262, ISO 21448, AUTOSAR, etc.) where applicable\n"
            f"3. Include code examples, tables, or structured data where helpful\n"
            f"4. Structure output with clear markdown headings (##, ###)\n"
            f"5. Be thorough but concise — prioritize actionable technical content\n"
            f"6. If you identify safety or compliance risks, flag them explicitly\n"
        )

    def _build_user_prompt(
        self, step_name: str, step_desc: str,
        context_files: List[str], user_instruction: str,
        step_index: int, workflow_steps: List[Dict[str, Any]],
    ) -> str:
        """Build user prompt for the step execution."""
        parts = [f"## Task: {step_name}\n"]

        if step_desc:
            parts.append(f"{step_desc}\n")

        # Add previous steps context
        if step_index > 0 and workflow_steps:
            parts.append("## Previous Steps Completed\n")
            for i in range(step_index):
                prev = workflow_steps[i]
                parts.append(f"- {prev.get('name', f'Step {i+1}')}")
            parts.append("")

        if context_files:
            parts.append("## Context Files\n")
            for f in context_files:
                parts.append(f"- {f}")
            parts.append("")

        if user_instruction:
            parts.append(f"## Additional Instructions\n{user_instruction}\n")

        parts.append(
            "\nPlease complete the analysis for this step. "
            "Structure your response with clear sections and include "
            "technical details, tables, and code where appropriate."
        )

        return "\n".join(parts)

    @staticmethod
    def _extract_code_blocks(text: str) -> str:
        """Extract code blocks from markdown text."""
        import re
        blocks = re.findall(r'```(?:\w+)?\n(.*?)```', text, re.DOTALL)
        return "\n\n".join(blocks) if blocks else ""

    def _normalize_domain(self, domain: str) -> str:
        """Normalize domain string to a known key."""
        domain_lower = domain.lower().replace("-", " ").replace("_", " ")
        if "adas" in domain_lower:
            return "adas"
        if "functional safety" in domain_lower or "safety" in domain_lower:
            return "functional safety"
        if "autosar" in domain_lower:
            return "autosar"
        if "sotif" in domain_lower:
            return "sotif"
        if "diagnostic" in domain_lower:
            return "diagnostics"
        return domain_lower
